export const INCREMENT_REQUESTED = 'counter/INCREMENT_REQUESTED';
export const INCREMENT = 'counter/INCREMENT';
export const DECREMENT_REQUESTED = 'counter/DECREMENT_REQUESTED';
export const DECREMENT = 'counter/DECREMENT';

export const FETCH_POST_SUCCESS = 'FETCH_POST/SUCCESS';
export const FETCH_POST_FAIL = 'FETCH_POST/FAIL';
export const FETCH_POST_FETCHING = 'FETCH_POST/FETCHING';
export const FETCH_USER_SUCCESS = 'FETCH_USER/SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER/FAIL';
export const FETCH_USER_FETCHING = 'FETCH_USER/FETCHING';
